version: '3.9'

services:
  web:
    build: .
    container_name: runsync
    command: >
      gunicorn runsync.asgi:application
      -k uvicorn.workers.UvicornWorker
      --bind 0.0.0.0:8000
      --log-level debug
      --access-logfile /app/logs/runsync-access.log
      --error-logfile /app/logs/runsync-error.log
    env_file:
      - .env
    ports:
      - "8000:8000"
    volumes:
      - ./logs:/app/logs
      - ./db:/app/db
    depends_on:
      - migrate
  migrate:
    build: .
    container_name: runsync-migrate
    command: >
      python manage.py migrate
    env_file:
      - .env
    volumes:
      - ./db:/app/db

  datadog-agent:
    image: datadog/agent:latest
    container_name: runsync-datadog-agent
    volumes:
      - ./datadog.yaml:/etc/datadog/datadog.yaml
      - ./logs:/logs
      # - /var/run/docker.sock:/var/run/docker.sock
      # - /proc:/host/proc:ro
      # - /sys/fs/cgroup/:/host/sys/fs/cgroup:ro
    expose:
      - 8126
    ports:
      - "8126:8126"
      - "8125:8125/udp"
    environment:
      - DD_API_KEY=${DD_API_KEY}
      - DD_SITE=datadoghq.com
      - DD_TAGS=env:production
      - DD_LOGS_ENABLED=true
      - DD_LOGS_CONFIG_CONTAINER_COLLECT_ALL=true
      - DD_CONTAINER_EXCLUDE=name:runsync-datadog-agent
      - DD_SITE=us5.datadoghq.com
    restart: always

